address: EQBn2fC7QEkGKB6ajJ3wnAQYC_GaXP5o5EP7Rak_NCww0MPW
symbol: MMC
name: Merphicoin
description: Utility token for the Merphi Music Group ecosystem
decimals: 9
image: https://i.ibb.co/R651cY1/IMG-4916.png
websites:
  - https://merphimusic.com
social:
  - https://t.me/merphimusicgroup
